services:
  - type: web
    name: photofit-pro
    env: python
    pythonVersion: '3.10.13'
    preBuildCommand: |
      apt-get update && apt-get install -y --no-install-recommends \
      build-essential \
      cmake \
      libopenblas-dev \
      liblapack-dev \
      libjpeg-dev \
      python3-dev \
      libboost-all-dev
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13

