# render.yaml
services:
  - type: web
    name: photofit-pro
    env: python
    pythonVersion: 3.10.13

    # Install system dependencies required to build dlib and OpenCV
    preBuildCommand: |
      apt-get update && apt-get install -y --no-install-recommends \
      build-essential \
      cmake \
      g++ \
      libopenblas-dev \
      liblapack-dev \
      libx11-dev \
      libgtk-3-dev \
      libboost-python-dev \
      libboost-thread-dev \
      libboost-system-dev \
      libjpeg-dev \
      libtiff-dev \
      libpng-dev \
      pkg-config \
      python3-dev

    buildCommand: pip install --upgrade pip && pip install -r requirements.txt

    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app

    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
